# Generated by Django 4.2.5 on 2023-09-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default=1, max_length=50, verbose_name='Название курса'),
            preserve_default=False,
        ),
    ]
