# Generated by Django 4.2.5 on 2023-09-21 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='surname',
        ),
    ]
